### ISSUE TITLE
リマインダーも自動に送る機能がほしい

### ISSUE THREAD

**Issue by snishiyama** [grocio/participants-recruitment-jp#3]
です。
案としては「実験まであと何日」みたいな列を用意して、そのセルに「(希望日時の日)−(今日)」という計算をさせて1になったときに規定の内容のメールを送るようなスクリプトを書けばいいのではないかと思います。

**Comment by grocio** [comment]
スプレッドシート上ですと、関数の実行のトリガーとして、フォームの送信時や起動時、値の変更時などイベントが起きた際に関数を実行することはできそうです。毎回起動して関数を走らせることもできるかと思いますが、できれば時間ベースで関数を実行したいです。googleカレンダーやgmailの機能に使えそうなものがあればそちらで設定することもできるかと思います。

**Comment by snishiyama** [comment]
作成できたのでそのうち反映します。

**Comment by snishiyama** [comment]
解決！！
